CREATE TABLE IF NOT EXISTS "substation"
(
    -- Substation primary key
    "id"         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Substation full name
    "name"       VARCHAR(255),
    -- Unique operational code/acronym of the substation
    "acronym"    VARCHAR(255) NOT NULL,
    -- City where the substation is located
    "city"       VARCHAR(255),
    -- Two-letter state code
    "state"      CHAR(2),
    -- Geographic latitude, decimal degrees (7 decimal places)
    "latitude"   NUMERIC(9, 7),
    -- Geographic longitude, decimal degrees (7 decimal places)
    "longitude"  NUMERIC(10, 7),
    -- Soft-activation flag; FALSE means the substation is disabled
    "active"     BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Record creation timestamp (set by the backend)
    "created_at" TIMESTAMPTZ  NOT NULL,
    -- Record last-update timestamp (set by the backend)
    "updated_at" TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY ("id")
);

COMMENT ON TABLE "substation" IS 'Electrical substations that host transformers';
COMMENT ON COLUMN "substation"."id" IS 'Substation primary key';
COMMENT ON COLUMN "substation"."name" IS 'Substation full name';
COMMENT ON COLUMN "substation"."acronym" IS 'Unique operational code/acronym of the substation';
COMMENT ON COLUMN "substation"."city" IS 'City where the substation is located';
COMMENT ON COLUMN "substation"."state" IS 'Two-letter state code';
COMMENT ON COLUMN "substation"."latitude" IS 'Geographic latitude, decimal degrees (7 decimal places)';
COMMENT ON COLUMN "substation"."longitude" IS 'Geographic longitude, decimal degrees (7 decimal places)';
COMMENT ON COLUMN "substation"."active" IS 'Soft-activation flag; FALSE means the substation is disabled';
COMMENT ON COLUMN "substation"."created_at" IS 'Record creation timestamp (set by the backend)';
COMMENT ON COLUMN "substation"."updated_at" IS 'Record last-update timestamp (set by the backend)';

CREATE TABLE IF NOT EXISTS "transformer"
(
    -- Transformer primary key
    "id"                   BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- FK to the substation that hosts this transformer
    "substation_id"        BIGINT       NOT NULL,
    -- Unique asset tag/operational identifier
    "tag"                  VARCHAR(255) NOT NULL UNIQUE,
    -- Manufacturer name
    "manufacturer"         VARCHAR(255),
    -- Unique manufacturer serial number
    "serial_number"        VARCHAR(255) NOT NULL,
    -- Year of manufacture
    "manufacture_year"     SMALLINT,
    -- Rated power in MVA
    "rated_power_mva"      NUMERIC(8, 2),
    -- Rated primary (high) voltage in kV
    "primary_voltage_kv"   NUMERIC(6, 2),
    -- Rated secondary (low) voltage in kV
    "secondary_voltage_kv" NUMERIC(6, 2),
    -- Insulating oil type; enum code mapped by the backend (mineral/vegetable/ester)
    "oil_type"             INTEGER      NOT NULL,
    -- Date the transformer entered operation
    "commissioning_date"   DATE,
    -- Operational status; enum code mapped by the backend (operation/maintenance/decommissioned)
    "status"               INTEGER      NOT NULL,
    -- Record creation timestamp (set by the backend)
    "created_at"           TIMESTAMPTZ  NOT NULL,
    -- Record last-update timestamp (set by the backend)
    "updated_at"           TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY ("id")
);

COMMENT ON TABLE "transformer" IS 'Power transformers monitored for condition assessment';
COMMENT ON COLUMN "transformer"."id" IS 'Transformer primary key';
COMMENT ON COLUMN "transformer"."substation_id" IS 'FK to the substation that hosts this transformer';
COMMENT ON COLUMN "transformer"."tag" IS 'Unique asset tag/operational identifier';
COMMENT ON COLUMN "transformer"."manufacturer" IS 'Manufacturer name';
COMMENT ON COLUMN "transformer"."serial_number" IS 'Unique manufacturer serial number';
COMMENT ON COLUMN "transformer"."manufacture_year" IS 'Year of manufacture';
COMMENT ON COLUMN "transformer"."rated_power_mva" IS 'Rated power in MVA';
COMMENT ON COLUMN "transformer"."primary_voltage_kv" IS 'Rated primary (high) voltage in kV';
COMMENT ON COLUMN "transformer"."secondary_voltage_kv" IS 'Rated secondary (low) voltage in kV';
COMMENT ON COLUMN "transformer"."oil_type" IS 'Insulating oil type; enum code mapped by the backend (mineral/vegetable/ester)';
COMMENT ON COLUMN "transformer"."commissioning_date" IS 'Date the transformer entered operation';
COMMENT ON COLUMN "transformer"."status" IS 'Operational status; enum code mapped by the backend (operation/maintenance/decommissioned)';
COMMENT ON COLUMN "transformer"."created_at" IS 'Record creation timestamp (set by the backend)';
COMMENT ON COLUMN "transformer"."updated_at" IS 'Record last-update timestamp (set by the backend)';

CREATE INDEX "transformer_index_0"
    ON "transformer" ("manufacturer");
CREATE INDEX "transformer_index_1"
    ON "transformer" ("status");

CREATE TABLE IF NOT EXISTS "analysis"
(
    -- Analysis primary key
    "id"             BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- FK to the sampled transformer
    "transformer_id" BIGINT      NOT NULL,
    -- Date the oil sample was collected
    "sample_date"    DATE        NOT NULL,
    -- Hydrogen concentration in ppm
    "h2"             NUMERIC(8, 2),
    -- Methane concentration in ppm
    "ch4"            NUMERIC(8, 2),
    -- Acetylene concentration in ppm
    "c2h2"           NUMERIC(8, 2),
    -- Ethylene concentration in ppm
    "c2h4"           NUMERIC(8, 2),
    -- Ethane concentration in ppm
    "c2h6"           NUMERIC(8, 2),
    -- Carbon monoxide concentration in ppm (paper degradation indicator)
    "co"             NUMERIC(8, 2),
    -- Carbon dioxide concentration in ppm (paper degradation indicator)
    "co2"            NUMERIC(8, 2),
    -- Record creation timestamp (set by the backend)
    "created_at"     TIMESTAMPTZ NOT NULL,
    -- Record last-update timestamp (set by the backend)
    "updated_at"     TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("id")
);

COMMENT ON TABLE "analysis" IS 'Dissolved gas analysis (DGA) samples taken from a transformer main tank';
COMMENT ON COLUMN "analysis"."id" IS 'Analysis primary key';
COMMENT ON COLUMN "analysis"."transformer_id" IS 'FK to the sampled transformer';
COMMENT ON COLUMN "analysis"."sample_date" IS 'Date the oil sample was collected';
COMMENT ON COLUMN "analysis"."h2" IS 'Hydrogen concentration in ppm';
COMMENT ON COLUMN "analysis"."ch4" IS 'Methane concentration in ppm';
COMMENT ON COLUMN "analysis"."c2h2" IS 'Acetylene concentration in ppm';
COMMENT ON COLUMN "analysis"."c2h4" IS 'Ethylene concentration in ppm';
COMMENT ON COLUMN "analysis"."c2h6" IS 'Ethane concentration in ppm';
COMMENT ON COLUMN "analysis"."co" IS 'Carbon monoxide concentration in ppm (paper degradation indicator)';
COMMENT ON COLUMN "analysis"."co2" IS 'Carbon dioxide concentration in ppm (paper degradation indicator)';
COMMENT ON COLUMN "analysis"."created_at" IS 'Record creation timestamp (set by the backend)';
COMMENT ON COLUMN "analysis"."updated_at" IS 'Record last-update timestamp (set by the backend)';

CREATE TABLE IF NOT EXISTS "diagnosis"
(
    -- Diagnosis primary key
    "id"                BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- FK to the source analysis (one diagnosis per analysis)
    "analysis_id"       BIGINT      NOT NULL UNIQUE,
    -- Fault code from Rogers Ratio method; enum code mapped by the backend
    "rogers_fault"      INTEGER,
    -- Fault code from Duval Triangle method; enum code mapped by the backend
    "duval_fault"       INTEGER,
    -- Fault code from IEC ratio method; enum code mapped by the backend
    "iec_fault"         INTEGER,
    -- Fault code from Doernenburg Ratio method; enum code mapped by the backend
    "doernenburg_fault" INTEGER,
    -- Final fault code from the backend weighted calculation; enum code mapped by the backend
    "final_fault"       INTEGER,
    -- Record creation timestamp (set by the backend)
    "created_at"        TIMESTAMPTZ NOT NULL,
    -- Record last-update timestamp (set by the backend)
    "updated_at"        TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("id")
);

COMMENT ON TABLE "diagnosis" IS 'Fault diagnosis derived from a single DGA analysis';
COMMENT ON COLUMN "diagnosis"."id" IS 'Diagnosis primary key';
COMMENT ON COLUMN "diagnosis"."analysis_id" IS 'FK to the source analysis (one diagnosis per analysis)';
COMMENT ON COLUMN "diagnosis"."rogers_fault" IS 'Fault code from Rogers Ratio method; enum code mapped by the backend';
COMMENT ON COLUMN "diagnosis"."duval_fault" IS 'Fault code from Duval Triangle method; enum code mapped by the backend';
COMMENT ON COLUMN "diagnosis"."iec_fault" IS 'Fault code from IEC ratio method; enum code mapped by the backend';
COMMENT ON COLUMN "diagnosis"."doernenburg_fault" IS 'Fault code from Doernenburg Ratio method; enum code mapped by the backend';
COMMENT ON COLUMN "diagnosis"."final_fault" IS 'Final fault code from the backend weighted calculation; enum code mapped by the backend';
COMMENT ON COLUMN "diagnosis"."created_at" IS 'Record creation timestamp (set by the backend)';
COMMENT ON COLUMN "diagnosis"."updated_at" IS 'Record last-update timestamp (set by the backend)';

CREATE TABLE IF NOT EXISTS "app_user"
(
    -- user primary key
    "id"            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Unique login username
    "username"      VARCHAR(255) NOT NULL,
    -- Hashed password
    "password_hash" VARCHAR(255) NOT NULL,
    -- User role; enum code mapped by the backend (USER/ADMIN)
    "role"          INTEGER      NOT NULL,
    -- Whether the account is enabled
    "active"        BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Record creation timestamp (set by the backend)
    "created_at"    TIMESTAMPTZ  NOT NULL,
    -- Record last-update timestamp (set by the backend)
    "updated_at"    TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY ("id")
);

COMMENT ON TABLE "app_user" IS 'Application users for in-app authentication and authorization';
COMMENT ON COLUMN "app_user"."id" IS 'user primary key';
COMMENT ON COLUMN "app_user"."username" IS 'Unique login username';
COMMENT ON COLUMN "app_user"."password_hash" IS 'Hashed password';
COMMENT ON COLUMN "app_user"."role" IS 'User role; enum code mapped by the backend (USER/ADMIN)';
COMMENT ON COLUMN "app_user"."active" IS 'Whether the account is enabled';
COMMENT ON COLUMN "app_user"."created_at" IS 'Record creation timestamp (set by the backend)';
COMMENT ON COLUMN "app_user"."updated_at" IS 'Record last-update timestamp (set by the backend)';

ALTER TABLE "transformer"
    ADD FOREIGN KEY ("substation_id") REFERENCES "substation" ("id")
        ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "analysis"
    ADD FOREIGN KEY ("transformer_id") REFERENCES "transformer" ("id")
        ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "diagnosis"
    ADD FOREIGN KEY ("id") REFERENCES "analysis" ("id")
        ON UPDATE CASCADE ON DELETE CASCADE;

-- Made with DrawDB: https://www.drawdb.app/editor